# Generated by Django 3.2.5 on 2021-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='datetime',
        ),
    ]
